autenticacao/urls.py
from django.conf.urls import url

from . import views

app_name = 'autenticacao'
urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
]

base/urls.py
from django.conf.urls import url

from . import views

app_name = 'base'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
]

denuncia/urls.py
from django.conf.urls import url

from .views import (
    AceitacaoDenuncia, AtualizacaoDenuncia, ConsultaDenuncia, DetalheDenuncia, EncaminhamentoDenuncia, ExclusaoDenuncia,
    NovaDenuncia, RejeicaoDenuncia)

app_name = 'denuncia'

urlpatterns = [
    url(r'^novo/$', NovaDenuncia.as_view(), name='novo'),
    url(r'^consulta/$', ConsultaDenuncia.as_view(), name='consulta'),
    url(r'^atualizacao/(?P<pk>[0-9]+)/$', AtualizacaoDenuncia.as_view(), name='atualizacao'),
    url(r'^detalhe/$', DetalheDenuncia.as_view(), name='detalhe'),
    url(r'^exclusao/$', ExclusaoDenuncia.as_view(), name='exclusao'),
    url(r'^aceitacao/$', AceitacaoDenuncia.as_view(), name='aceitacao'),
    url(r'^rejeicao/$', RejeicaoDenuncia.as_view(), name='rejeicao'),
    url(r'^encaminhamento/$', EncaminhamentoDenuncia.as_view(), name='encaminhamento'),
]

urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from settings import MEDIA_ROOT, MEDIA_URL

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url('', include('base.urls')),
    url(r'^autenticacao/', include('autenticacao.urls')),
    url(r'^denuncia/', include('denuncia.urls')),
    url(r'^mobilizacao/', include('mobilizacao.urls')),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

base/models.py
# from django.db import models

# Create your models here.

base/views.py
from django.shortcuts import render
from django.views import View


class IndexView(View):
    def get(self, request):
        return render(request, 'base/index.html')

base/templates/base.html
{% load static %}

<!DOCTYPE HTML>
<html lang="pt">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

		<!-- Meta para dispositivos móveis -->
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

		<title>Denúncias Ambientais</title>

		<!-- jQuery -->
		<script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>

		<!-- Semantic UI -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.13/semantic.min.js" integrity="sha256-Bhi6GMQ/72uYZcJXCJ2LToOIcN3+Cx47AZnq/Bw1f7A=" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.13/components/popup.min.js" integrity="sha256-4qXxQxHWDAy2mIrLYhQZMk72v21R2iYYtlGk/t3wGkA=" crossorigin="anonymous"></script>
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.13/semantic.min.css" integrity="sha256-/Z28yXtfBv/6/alw+yZuODgTbKZm86IKbPE/5kjO/xY=" crossorigin="anonymous" />
		<link rel="stylesheet" href="{% static 'css/app.css' %}" />
	</head>

	<body>
		{% block body_begin_scripts %}
		{% endblock %}

		<!-- Menu -->
		<nav class="ui large menu">
			<div class="ui container">
				<a class="item" href="{% url 'base:index' %}">
					<i class="home icon" data-content="Início"></i>
				</a>
				<a class="item" href="{% url 'denuncia:consulta' %}">
					Denúncias
				</a>

				<a class="item" href="">
					Mobilização Ambiental
				</a>
				<a class="item" href="http://observatorioambien1.wixsite.com/obsambiental/boas-praticas">
					Boas Práticas
				</a>

				<div class="right menu">
					{% if user.is_authenticated %}
						<a class="item" href="{% url 'autenticacao:logout' %}">
							<i class="sign out icon"></i> Sair
						</a>
					{% else %}
						<a class="item" href="{% url 'autenticacao:login' %}">
							<i class="sign in icon"></i> Entrar
						</a>
					{% endif %}
				</div>
			</div>
		</nav>

		<br>

		{% block content %}
		{% endblock %}

		<br>

		{% if messages %}
			<div class="ui mini modal">
				<div class="header">
					Denúncia ambiental
				</div>
				<div class="content">
					{% for message in messages %}
						<p>{{ message }}</p>
					{% endfor %}
				</div>
				<div class="actions">
					<div class="ui teal ok button">
						<i class="checkmark icon"></i> OK
					</div>
				</div>
			</div>
		{% endif %}

		{% block body_end_scripts %}
			<script type="text/javascript">
				$(function() {
					$('.mini.modal')
						.modal('setting', {duration: 300})
						.modal('show');

					$('.icon').popup();
				});
			</script>
		{% endblock %}
	</body>
</html>