denuncia/urls.py
from django.conf.urls import url

from .views import (
    AceitacaoDenuncia, AtualizacaoDenuncia, ConsultaDenuncia, DetalheDenuncia, EncaminhamentoDenuncia, ExclusaoDenuncia,
    NovaDenuncia, RejeicaoDenuncia)

app_name = 'denuncia'

urlpatterns = [
    url(r'^novo/$', NovaDenuncia.as_view(), name='novo'),
    url(r'^consulta/$', ConsultaDenuncia.as_view(), name='consulta'),
    url(r'^atualizacao/(?P<pk>[0-9]+)/$', AtualizacaoDenuncia.as_view(), name='atualizacao'),
    url(r'^detalhe/$', DetalheDenuncia.as_view(), name='detalhe'),
    url(r'^exclusao/$', ExclusaoDenuncia.as_view(), name='exclusao'),
    url(r'^aceitacao/$', AceitacaoDenuncia.as_view(), name='aceitacao'),
    url(r'^rejeicao/$', RejeicaoDenuncia.as_view(), name='rejeicao'),
    url(r'^encaminhamento/$', EncaminhamentoDenuncia.as_view(), name='encaminhamento'),
]

urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from settings import MEDIA_ROOT, MEDIA_URL

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url('', include('base.urls')),
    url(r'^autenticacao/', include('autenticacao.urls')),
    url(r'^denuncia/', include('denuncia.urls')),
    url(r'^mobilizacao/', include('mobilizacao.urls')),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

denuncia/models.py
from django.db.models import (
    CharField, DateTimeField, EmailField, FloatField, ForeignKey, ImageField, IntegerField, Model)

MAX_LENGTH = 100


class EstadoDenuncia(Model):
    nome = CharField(max_length=MAX_LENGTH)

    def __str__(self):
        return self.nome


class Localizacao(Model):
    cep = CharField(max_length=9)
    rua = CharField(max_length=MAX_LENGTH)
    bairro = CharField(max_length=MAX_LENGTH)
    cidade = CharField(max_length=MAX_LENGTH)
    complemento = CharField(max_length=MAX_LENGTH, blank=True, null=True)
    numero = IntegerField(blank=True, null=True)
    pais = CharField(max_length=MAX_LENGTH, blank=True, null=True)
    latitude = FloatField(blank=True, null=True)
    longitude = FloatField(blank=True, null=True)

    def __str__(self):
        return self.cep


# Municipal, estadual, federal etc.
class TipoOrgaoCompetente(Model):
    nome = CharField(max_length=MAX_LENGTH)

    def __str__(self):
        return self.nome


# IAP, IBAMA, ANA etc.
class OrgaoCompetente(Model):
    nome = CharField(max_length=MAX_LENGTH)
    sigla = CharField(max_length=10)
    telefone = CharField(max_length=10)
    email = EmailField(blank=True, null=True)
    site = CharField(max_length=MAX_LENGTH, blank=True, null=True)
    nome_responsavel = CharField(max_length=MAX_LENGTH)

    tipo_orgao = ForeignKey(TipoOrgaoCompetente)
    endereco = ForeignKey(Localizacao)

    def __str__(self):
        return self.nome


class Legislacao(Model):
    nome = CharField(max_length=MAX_LENGTH)
    numero_lei = IntegerField()
    descricao = CharField(max_length=MAX_LENGTH)

    orgao_competente = ForeignKey(OrgaoCompetente)

    def __str__(self):
        return self.nome


class AreaDenuncia(Model):
    nome = CharField(max_length=MAX_LENGTH, help_text='Ar, solos, vegetação, animais, água, contaminação por agrotóxicos')

    legislacao = ForeignKey(Legislacao, blank=True, null=True)

    def __str__(self):
        return self.nome


class CategoriaDenuncia(Model):
    nome = CharField(max_length=MAX_LENGTH, help_text='No caso de ar: poluição, fumaça etc.')

    area_denuncia = ForeignKey(AreaDenuncia)

    def __str__(self):
        return self.nome


# https://github.com/django/djangoproject.com/blob/master/accounts/py
# https://github.com/archlinux/archweb
class Usuario(Model):
    nome = CharField(max_length=MAX_LENGTH)
    email = EmailField()
    data_criacao = DateTimeField(auto_now_add=True)
    # cpf = CharField(max_length=MAX_LENGTH, blank=True, null=True)
    # nome_usuario = CharField(max_length=MAX_LENGTH, blank=True, null=True)
    # senha = CharField(max_length=MAX_LENGTH, blank=True, null=True)
    # salt = CharField(max_length=MAX_LENGTH, blank=True, null=True)
    #  user = OneToOneField(User, related_name='usuario')

    def __str__(self):
        return self.nome


class Denuncia(Model):
    descricao = CharField(max_length=MAX_LENGTH * 10, blank=True, null=True)
    data_ocorrencia = DateTimeField()

    categoria_denuncia = ForeignKey(CategoriaDenuncia)
    localizacao = ForeignKey(Localizacao)
    estado_denuncia = ForeignKey(EstadoDenuncia, blank=True, null=True)
    usuario = ForeignKey(Usuario, blank=True, null=True)  # None/NULL quer dizer que a denúncia é anônima


class ArquivoDenuncia(Model):
    nome = CharField(max_length=MAX_LENGTH)
    arquivo = ImageField(upload_to='uploads/')
    data_envio = DateTimeField(auto_now_add=True)

    denuncia = ForeignKey(Denuncia)

    def __str__(self):
        return self.nome


class RelatorioDenuncia(Model):
    texto = CharField(max_length=MAX_LENGTH)
    data = DateTimeField()

    denuncia = ForeignKey(Denuncia)
    Legislacao = ForeignKey(Legislacao)

    def __str__(self):
        return self.texto

denuncia/views.py
import os

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.http import urlencode
from django.utils.text import slugify
from django.views.generic import View
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from settings import UPLOADS_URL

from .forms import AreaDenunciaForm, ArquivoDenuncia, ArquivoDenunciaForm, DenunciaForm, LocalizacaoForm, UsuarioForm
from .models import AreaDenuncia, Denuncia, EstadoDenuncia


def salvar_arquivo_denuncia(arquivo_form, denuncia):
    # Padroniza nome do arquivo e salva
    # arquivo_denuncia = arquivo_form.instance
    arquivo_denuncia = arquivo_form.save(commit=False)
    arquivo_denuncia.denuncia = denuncia
    nome = os.path.splitext(arquivo_denuncia.arquivo.name)[0]
    extensao = os.path.splitext(arquivo_denuncia.arquivo.name)[1]
    arquivo_denuncia.arquivo.name = slugify(nome, allow_unicode=True) + extensao
    arquivo_denuncia.nome = arquivo_denuncia.arquivo.name
    # arquivo_form.save()
    arquivo_denuncia.save()


class NovaDenuncia(CreateView):
    def get(self, request):
        initial_usuario = {
            'nome': 'nome teste',
            'email': 'emailteste@provedor.com',
        }
        initial_localizacao = {
            'cep': '85867-900',
            'rua': 'rua teste',
            'bairro': 'bairro teste',
            'cidade': 'cidade teste',
            'complemento': 'complemento teste',
            'numero': '47',
        }
        initial_area = {
            'nome': AreaDenuncia.objects.get(nome='Ar')
        }

        context = {
            'denuncia_form': DenunciaForm(prefix='denuncia'),
            'usuario_form': UsuarioForm(prefix='usuario', initial=initial_usuario),
            'localizacao_form': LocalizacaoForm(prefix='localizacao', initial=initial_localizacao),
            'area_form': AreaDenunciaForm(prefix='area', initial=initial_area),
            'arquivo_form': ArquivoDenunciaForm(prefix='arquivo'),
            'categoria_selecionada': initial_area['nome'].categoriadenuncia_set.first(),
        }

        return render(request, 'denuncia/denuncia_form.html', context)

    @transaction.atomic
    def post(self, request):
        denuncia_form = DenunciaForm(request.POST, prefix='denuncia')
        usuario_form = UsuarioForm(request.POST, prefix='usuario')
        localizacao_form = LocalizacaoForm(request.POST, prefix='localizacao')
        area_form = AreaDenunciaForm(request.POST, prefix='area')
        arquivo_form = ArquivoDenunciaForm(request.POST, request.FILES, prefix='arquivo')

        # Caso todos os forms da denúncia sejam válidos
        if (denuncia_form.is_valid() and
                usuario_form.is_valid() and
                localizacao_form.is_valid() and
                area_form.is_valid() and
                arquivo_form.is_valid()):
            localizacao = localizacao_form.save()
            usuario = usuario_form.save()

            # Popula os restantes
            denuncia = denuncia_form.save(commit=False)
            denuncia.localizacao = localizacao
            denuncia.usuario = usuario
            denuncia.estado_denuncia = EstadoDenuncia.objects.get(nome='Pendente (em verificação)')
            denuncia.save()

            if len(request.FILES) != 0:
                salvar_arquivo_denuncia(arquivo_form, denuncia)

            messages.success(request, 'Denúncia salva com sucesso.')
            messages.success(request, 'Nº de protocolo: {}'.format(denuncia.pk))
            return redirect('/denuncia/detalhe/?{}'.format(urlencode({'pk': denuncia.pk})))

        # Caso alguns dos forms da denúncia não seja válido
        context = {
            'denuncia_form': denuncia_form,
            'usuario_form': usuario_form,
            'localizacao_form': localizacao_form,
            'area_form': area_form,
            'categoria_selecionada': denuncia_form.instance.categoria_denuncia,
            'arquivo_form': arquivo_form,
        }
        messages.error(request, 'Existem erros em seu formulário.')
        return render(request, 'denuncia/denuncia_form.html', context)


class DetalheDenuncia(DetailView):
    model = Denuncia
    objeto = None

    def get_object(self):
        try:
            pk = self.request.GET.get('pk')
            self.objeto = get_object_or_404(Denuncia, pk=pk)
            return self.objeto
        except Http404:
            messages.error(self.request, 'Denúncia não encontrada.')

    def render_to_response(self, context):
        if not self.objeto:
            return redirect('denuncia:consulta')

        context['UPLOADS_URL'] = UPLOADS_URL
        return super().render_to_response(context)


class ConsultaDenuncia(ListView):
    model = Denuncia

    def get_queryset(self):
        return Denuncia.objects.all()


class AtualizacaoDenuncia(LoginRequiredMixin, UpdateView):
    def get(self, request, pk):
        denuncia = get_object_or_404(Denuncia, pk=pk)
        usuario = denuncia.usuario
        localizacao = denuncia.localizacao

        context = {
            'denuncia_form': DenunciaForm(instance=denuncia, prefix='denuncia'),
            'usuario_form': UsuarioForm(instance=usuario, prefix='usuario'),
            'localizacao_form': LocalizacaoForm(instance=localizacao, prefix='localizacao'),
            'area_form': AreaDenunciaForm(prefix='area', initial={'nome': denuncia.categoria_denuncia.area_denuncia}),
            'categoria_selecionada': denuncia.categoria_denuncia,
        }

        try:
            arquivo_denuncia = ArquivoDenuncia.objects.get(denuncia=denuncia)
            context['arquivo_form'] = ArquivoDenunciaForm(instance=arquivo_denuncia, prefix='arquivo')
        except ArquivoDenuncia.DoesNotExist:
            context['arquivo_form'] = ArquivoDenunciaForm(prefix='arquivo')

        return render(request, 'denuncia/denuncia_form.html', context)

    @transaction.atomic
    def post(self, request, pk):
        denuncia = get_object_or_404(Denuncia, pk=pk)

        denuncia_form = DenunciaForm(request.POST, instance=denuncia, prefix='denuncia')
        usuario_form = UsuarioForm(request.POST, instance=denuncia.usuario, prefix='usuario')
        localizacao_form = LocalizacaoForm(request.POST, instance=denuncia.localizacao, prefix='localizacao')
        area_form = AreaDenunciaForm(request.POST, prefix='area')

        # Checa se a denúncia contém arquivos
        try:
            arquivo_denuncia = ArquivoDenuncia.objects.get(denuncia=denuncia)
            arquivo_form = ArquivoDenunciaForm(request.POST, request.FILES, instance=arquivo_denuncia, prefix='arquivo')
        except ArquivoDenuncia.DoesNotExist:
            arquivo_form = ArquivoDenunciaForm(request.POST, request.FILES, prefix='arquivo')

        if (denuncia_form.is_valid() and
                usuario_form.is_valid() and
                localizacao_form.is_valid() and
                area_form.is_valid() and
                arquivo_form.is_valid()):
            localizacao = localizacao_form.save()
            usuario = usuario_form.save()

            # Popula os restantes
            denuncia = denuncia_form.save(commit=False)
            denuncia.localizacao = localizacao
            denuncia.usuario = usuario
            denuncia.save()

            if len(request.FILES) != 0:
                salvar_arquivo_denuncia(arquivo_form, denuncia)

            messages.success(request, 'Denúncia salva com sucesso.')
            return redirect('denuncia:consulta')

        # Caso alguns dos forms da denúncia não seja válido
        context = {
            'denuncia_form': denuncia_form,
            'usuario_form': usuario_form,
            'localizacao_form': localizacao_form,
            'area_form': area_form,
            'categoria_selecionada': denuncia.categoria_denuncia,
            'arquivo_form': arquivo_form,
        }

        return render(request, 'denuncia/denuncia_form.html', context)


class ExclusaoDenuncia(LoginRequiredMixin, DeleteView):
    def post(self, request):
        denuncia = get_object_or_404(Denuncia, pk=request.POST['pk'])
        # TODO: deletar arquivos relacionados à denúncia
        # arquivo_denuncia = ArquivoDenuncia.objects.get(denuncia=denuncia)
        # num_delecoes_arquivo = arquivo_denuncia.delete()

        num_delecoes_denuncia = denuncia.delete()
        if num_delecoes_denuncia:
            messages.success(request, 'Denúncia removida com sucesso.')
        else:
            messages.error(request, 'Erro na remoção da denúncia.')

        return redirect('denuncia:consulta')


class AceitacaoDenuncia(LoginRequiredMixin, View):
    def post(self, request):
        denuncia = get_object_or_404(Denuncia, pk=request.POST['pk'])

        denuncia.estado_denuncia = EstadoDenuncia.objects.get(nome='Aceita')
        denuncia.save()

        return redirect('denuncia:consulta')


class RejeicaoDenuncia(LoginRequiredMixin, View):
    def post(self, request):
        denuncia = get_object_or_404(Denuncia, pk=request.POST['pk'])

        denuncia.estado_denuncia = EstadoDenuncia.objects.get(nome='Rejeitada')
        denuncia.save()

        return redirect('denuncia:consulta')


class EncaminhamentoDenuncia(LoginRequiredMixin, View):
    def post(self, request):
        denuncia = get_object_or_404(Denuncia, pk=request.POST['pk'])

        denuncia.estado_denuncia = EstadoDenuncia.objects.get(nome='Encaminhada ao órgão competente')
        denuncia.save()

        return redirect('denuncia:consulta')

denuncia/templates/denuncia/denuncia_detail.html
{% extends 'base.html' %}

{% block content %}
	<div class="ui form container">

		<b>Nº DE PROTOCOLO</b>: {{ object.pk }}
		<br>
		<b>ESTADO</b>: {{ object.estado_denuncia.nome }}
		<br>

		<h4 class="ui dividing header">Informações pessoais</h4>
		<div class="two fields">
			<div class="field">
				<label>Nome</label>
				{{ object.usuario.nome }}
			</div>
			<div class="field">
				<label>Email</label>
				{{ object.usuario.email }}
			</div>
		</div>

		<h4 class="ui dividing header">Localização da ocorrência</h4>
		<div class="three fields">
			<div class="field">
				<label>CEP</label>
				{{ object.localizacao.cep }}
			</div>
			<div class="field">
				<label>Número</label>
				{{ object.localizacao.numero }}
			</div>
			<div class="field">
				<label>Complemento</label>
				{{ object.localizacao.complemento }}
			</div>
		</div>

		<div class="two fields">
			<div class="field">
				<label>Rua</label>
				{{ object.localizacao.rua }}
			</div>
			<div class="field">
				<label>Bairro</label>
				{{ object.localizacao.bairro }}
			</div>
			<div class="field">
				<label>Cidade</label>
				{{ object.localizacao.cidade }}
			</div>
		</div>

		<h4 class="ui dividing header">Data e hora da ocorrência</h4>
		<div class="four fields">
			<div class="field">
				<label>Data e hora da ocorrência</label>
				{{ object.data_ocorrencia }}
			</div>
		</div>

		<h4 class="ui dividing header">Área, categoria e descrição da ocorrência</h4>
		<div class="two fields">
			<div class="field">
				<label>Área de incidente ambiental</label>
				{{ object.categoria_denuncia.area_denuncia.nome }}
			</div>
			<div class="field">
				<label>Categoria de incidente ambiental</label>
				{{ object.categoria_denuncia.nome }}
			</div>
		</div>

		<br>

		<div class="field">
			<label>Descrição</label>
			{{ object.descricao }}
		</div>

		{% if object.arquivodenuncia_set.all %}
			<div class="row">
				<h5>Arquivos</h5>
				<div class="ui medium image">
					{% for arquivo in object.arquivodenuncia_set.all %}
						<a href="{{ UPLOADS_URL }}{{ arquivo.nome }}">
							<img src="{{ UPLOADS_URL }}{{ arquivo.nome }}">
						</a>
					{% endfor %}
				</div>
			</div>
		{% endif %}

		<br>

		<div class="row" style="text-align: right;">
			<a href="{% url 'denuncia:consulta' %}" class="ui button">
				Voltar
			</a>
		</div>

	</div>
{% endblock %}

denuncia/templates/denuncia/denuncia_list.html
{% extends 'base.html' %}

{% block content %}
	<div class="ui container">
		<h4 class="ui dividing header">Cadastrar denúncia ambiental</h4>
		<a href="{% url 'denuncia:novo' %}" class="ui labeled icon button">
			<i class="teal plus icon"></i> Nova denúncia
		</a>

		<h4 class="ui dividing header">Pesquisar denúncia ambiental</h4>
		<form class="ui form" method="get" action="{% url 'denuncia:detalhe' %}">
			<div class="four fields">
				<div class="field">
					<label>Protocolo</label>
					<div class="ui action input">
						<input type="number" name="pk" id="pk" required autofocus>
						<button class="ui icon button" type="submit" data-content="Pesquisar">
							<i class="search icon"></i>
						</button>
					</div>
				</div>
			</div>
		</form>

		{% if user.is_authenticated %}
			<h3 class="ui center aligned dividing header">Lista de denúncias</h3>

			<table class="ui celled striped table">
				<thead>
					<th>Protocolo</th>
					<th>Nome</th>
					<th>Data de ocorrência</th>
					<th>Área de incidente</th>
					<th>Categoria de incidente</th>
					<th>Endereço</th>
					<th>Descrição</th>
					<th>Estado</th>
					<th>Ação</th>
				</thead>
				<tbody>
					{% for denuncia in object_list %}
						<tr>
							<td>{{ denuncia.pk }}</td>
							<td>{{ denuncia.usuario }}</td>
							<td>{{ denuncia.data_ocorrencia }}</td>
							<td>{{ denuncia.categoria_denuncia.area_denuncia }}</td>
							<td>{{ denuncia.categoria_denuncia }}</td>
							<td>{{ denuncia.localizacao.cep }}, {{ denuncia.localizacao.rua }}, {{ denuncia.localizacao.bairro }}, {{ denuncia.localizacao.complemento }}</td>
							<td>{{ denuncia.descricao }}</td>
							<td>{{ denuncia.estado_denuncia.nome }}</td>
							<td>
								<a href="{% url 'denuncia:atualizacao' denuncia.pk %}" class="ui compact icon button" data-content="Editar">
									<i class="teal edit icon"></i>
								</a>
								<form method="post" action="{% url 'denuncia:exclusao' %}" onsubmit="return confirm('Deseja realmente remover a denúncia?');">
									{% csrf_token %}
									<input type="hidden" name="pk" value="{{ denuncia.pk }}">
									<button class="ui compact icon button" type="submit" data-content="Remover">
										<i class="teal erase icon"></i>
									</button>
								</form>
								<form method="post" action="{% url 'denuncia:aceitacao' %}">
									{% csrf_token %}
									<input type="hidden" name="pk" value="{{ denuncia.pk }}">
									<button class="ui compact icon button" type="submit" data-content="Aceitar">
										<i class="teal checkmark icon"></i>
									</button>
								</form>
								<form method="post" action="{% url 'denuncia:rejeicao' %}">
									{% csrf_token %}
									<input type="hidden" name="pk" value="{{ denuncia.pk }}">
									<button class="ui compact icon button" type="submit" data-content="Rejeitar">
										<i class="teal remove icon"></i>
									</button>
								</form>
								<form method="post" action="{% url 'denuncia:encaminhamento' %}">
									{% csrf_token %}
									<input type="hidden" name="pk" value="{{ denuncia.pk }}">
									<button class="ui compact icon button" type="submit" data-content="Encaminhar ao órgão competente">
										<i class="teal external share icon"></i>
									</button>
								</form>
							</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		{% endif %}

		<br>
		<br>

	</div>
{% endblock %}